italia/developers-italia-onboarding

package-lock.json, package.json, src/email-sent.js, src/get-jwt-key.js
In questa PR si e' sviluppato un meccanismo di verifica delle URL che si andranno a registrare.
=> Fix #2 - Verifica URL

.circleci/config.yml
Adding a circleci pass to all branches (basically removing filters on master only). @sebbalex
=> Add circleci pass to all branches

public/assets/js/constants.js, public/assets/js/main.js
Now Ricerca Amministrazione field is enhanced by:
- Query size limits, query specific for inner offices
- Query are now enforced and more specific on what user is searching for
- Styling administration field search results
=> Ricerca Amministrazione query enhancement

src/tpl/email-sent.html
Adding more information regarding the PEC sender and the timings. 
@sebbalex @alranel please change it as you wish.
=> Add PEC sender info

src/tpl/main-content.html
This PR improves the text of the onboarding page, to clarify several things that were not fully explained, generating confusion or anxiety in users.
=> Improve the text for better clarity

public/assets/css/main.css
It fixes the label size in different views.
=> Label size in mobile view are rendered correctly.

.circleci/config.yml, Dockerfile, package-lock.json, package.json, public/assets/css/main.css
Bump Bootstrap Italia to 1.3.5
Integrate CD to CI pipeline
=> CD -> CI, bump BI

Dockerfile, public/assets/js/constants.js, public/assets/js/main.js
New data came from:
https://www.indicepa.gov.it/public-services/opendata-read-service.php?dstype=FS&filename=pec.txt
which has flat data instead of nested, less complexity.
Apparently, that file contains everything we need except for "tipo_amm" which the crawler could easily join from the other CSV files.
This is also related to [italia/developers-italia-backend#98](https://github.com/italia/developers-italia-backend/pull/98) with a static pointer to new index (`indicepa_pec`).
#72
=> AOO search improvements

.circleci/config.yml, package-lock.json, package.json, src/validator.js, test/validator.js
=> Make URLs with spaces pass the onboarding.

src/register-confirm.js, src/registered.js, src/tpl/register-confirm.html
This aims to enforce the duplicate entries check, it will prevents at any registration step to insert data already present in database.
This will also mitigate #83
=> Duplicate entries check enforced

src/registered.js
=> DB is not reloaded before writes

src/validation-error-message.js, src/validator.js
Hello,
I've translated all the Italian comments I could find in the code.
It should be all fine. Please, let me know otherwise.
Fix #129
=> Translated into English some comments in the code

public/index.html, src/tpl/main-content.html
Fix #124.
(also, test the Continuous Deployment pipeline is running correctly)
=> Simplify text and use correct headings rank.

package-lock.json, package.json
=> chore: update nodemailer

public/index.html, src/home.js
Being able to tell the deployed app version is useful for debugging
and also to make sure whether the app was deployed properly.
=> feat: add the app version in the HTML source

package-lock.json, package.json
Upgrade pm2 package to fix a security issue in netmask (CVE-2021-28918).
=> chore: upgrade pm2 package

.github/workflows/test_and_publish_docker_image.yml
* git tags starting with "v" (eg. v0.1.0) will result in a
italia/developers-italia-onboarding:v0.1.0 image.
* Commits to master will result in
italia/developers-italia-onboarding:master
* Both will create a italia/developers-italia-onboarding:{sha} tag
=> chore: build and push Docker image on tags

src/tpl/faq.html
=> fix: use the correct text for the FAQs and reformat the file

public/index.html
=> fix: legal URL

package-lock.json, package.json, server.js
=> feat: add logging

src/tpl/faq.html, src/tpl/register-confirm.html
=> fix: better layout in confirmation and faq pages

public/index.html
=> feat: remove the cookie dialog, we don't send any cookies

src/config.js, src/registered.js
chore: fix paseto key config name and add description field
=> chore: fix paseto key config name and add description field

src/registered.js
feat: add conditional POST or PATCH to add a publisher
Add alternativeId field to API to create a publisher
=> feat: add conditional POST or PATCH to add a publisher

src/register-fast-onboarding.js, src/registered.js
See https://github.com/italia/developers-italia-onboarding/pull/238#issuecomment-2432966530.
=> fix: keep `group` field in codeHosting
